### ISSUE TITLE
how to render the result

### ISSUE THREAD

**Issue by akchain** [qzane/textured_smplx#1]
hi, thanks for your work. 
Given the .obj file and the texture_smpl.png how can I render the 3d result as you did? Is it done by code or tools? Thanks.

**Comment by qzane** [comment]
Oh, it's just a screenshot from [MeshLab](https://www.meshlab.net/). If you want to render the result with code maybe you can try [pyrender](https://github.com/mmatl/pyrender).

**Comment by Wmelon0325** [comment]
could you provide method that adding texture to 3d smpl avatar in MeshLab , please

**Comment by AlyanQ** [comment]
Any update on this? I am trying to apply the textures produced by this repo but I am not able to.

**Comment by qzane** [comment]
You can refer to this gist: https://gist.github.com/qzane/60545ad8c6842381685e185900286223
There are two files, by modifying the map_Kd line in "template.obj.mtl" you can change the texture image, and by modifying the lines that begins with 'v' in the file "std_male.obj" you can change the body pose. For smplx models.

**Comment by qzane** [comment]
> Any update on this? I am trying to apply the textures produced by this repo but I am not able to.

You can refer to this gist: https://gist.github.com/qzane/60545ad8c6842381685e185900286223
There are two files, by modifying the map_Kd line in "template.obj.mtl" you can change the texture image, and by modifying the lines that begins with 'v' in the file "std_male.obj" you can change the body pose. For smplx models.

**Comment by qzane** [comment]
> Any update on this? I am trying to apply the textures produced by this repo but I am not able to.

You only need to put the new texture image in the "models" folder and modify the name of texture image in https://github.com/qzane/textured_smplx/blob/main/models/template.obj.mtl#L13

**Comment by hshreeshail** [comment]
> hi, thanks for your work. Given the .obj file and the texture_smpl.png how can I render the 3d result as you did? Is it done by code or tools? Thanks.

You can use the Mesh library https://github.com/MPI-IS/mesh. After installing, the following lines of code should suffice (this is what I use)
```
from psbody.mesh import Mesh, MeshViewers

smpl = Mesh(filename = '.obj filename here')
smpl.set_texture_image('texture_smpl.png')
mvs = MeshViewers((1, 1))
mvs[0][0].set_static_meshes([smpl])
mvs[0][0].save_snapshot('save_image_path.png')
```
