### ISSUE TITLE
how to run the PGN model?

### ISSUE THREAD

**Issue by Wmelon0325** [qzane/textured_smplx#2]
could you make the PGN outputs from CIHP_PGN model , please?
i don't know how to run the PGN model

**Comment by Wmelon0325** [comment]
i solved it ! thank you

**Comment by AlyanQ** [comment]
Could you give a guide on how you ran the PGN model?

**Comment by qzane** [comment]
> Could you give a guide on how you ran the PGN model?

PGN model is here: https://github.com/Engineering-Course/CIHP_PGN
to generate the dataset for PGN model, here is a script for your reference: https://gist.github.com/qzane/4d07b7551914f97f2bf8b9c79138ab14
