### ISSUE TITLE
Wrong result when mapping the texture file to smplx model.

### ISSUE THREAD

**Issue by JunfengLiu1** [qzane/textured_smplx#4]
Hey,When I used [https://github.com/qzane/textured_smplx/blob/main/data/obj1/texture_smplx.png](url) and map it to the smplx obj file with UV map downloaded in smplx website,It worked fine.(Like the screenshot below)
![2023-04-04 18-17-42 的屏幕截图](https://user-images.githubusercontent.com/122666174/229762063-7eeea4b8-bfe4-4e14-9d48-3fd92cf1ea27.png)
However,when I map it to the smplx FBX file generater with SMPLX Blender Add On,the result was wrong.(Like the screenshot below).
![2023-04-04 18-20-06 的屏幕截图](https://user-images.githubusercontent.com/122666174/229762555-deaa0e48-d3b6-43c4-a136-dcf94671f265.png)
It seems that the uvmap is not compatible with the texture.I have tried so many ways to fix it,but failed.
Can you give me a way to fix it?Thanks a lot

**Comment by qzane** [comment]
Sorry I'm not familiar with FBX and Blender so I don't know what's the problem. But the triangles in your second images seems to be a SMPL texture map rather than a SMPLX texture map, maybe you try the SMPL texture and see if it works.

**Comment by JunfengLiu1** [comment]
Thank you for your answer.I tried SMPL texture (texture_smpl.pnj in obj1),but the result didn't seem good:
![2023-04-13 20-35-11 的屏幕截图](https://user-images.githubusercontent.com/122666174/231760095-f3dd5aef-3b78-42d8-ab89-baf62ca0a550.png)
I also tried the smplx-in-unity downloaded from official website,but the result was the same like this:
![错误](https://user-images.githubusercontent.com/122666174/231760550-b56d8f39-775d-4e13-a3a8-7d61a9dbf393.png)
And here is my model:
[smplx-neutral-basic.zip](https://github.com/qzane/textured_smplx/files/11222256/smplx-neutral-basic.zip)
I'm trying to map my own texture to smplx model and use it in game pipeline using textured_smplx.Could you please give me a rigging smplx model （binded with skeleton）which can use the texture generated by textured_smplx correctly?I will appreciate that so much.

**Comment by JunfengLiu1** [comment]
Fix it,using blender to convert plugin's uv map to smplx_uv.obj's.
