### ISSUE TITLE
Using the same images,the result was wrong

### ISSUE THREAD

**Issue by JunfengLiu1** [qzane/textured_smplx#6]
Hey,when I used the images you provided and ran the all code to gernerated texture,the result was different.Here is the screenshoot below(The right was mine,which was different from the result provided by this repo):
![111111111111](https://user-images.githubusercontent.com/122666174/234565994-1bba5c57-2658-4c13-bcc9-2eb0918d1a75.png)
And here is the render result:
![2023-04-26 19-50-54 的屏幕截图](https://user-images.githubusercontent.com/122666174/234566282-037bf22c-57a5-43f9-a719-8ce85a5bc85d.png)
Obviously,the arm part was strange.I had tried many other images took by myself,but the result was all the same.Is there any way to fix?Thanks so much!

**Comment by JunfengLiu1** [comment]
@qzane And  I think it was PGN's problem.Here is mine PGN result and the repo's.
[PGN.zip](https://github.com/qzane/textured_smplx/files/11341525/PGN.zip)
Although their difference is small, it does lead to a difference in the results.
Maybe the reason was picture resolution.I use [the line in your code](https://gist.github.com/qzane/4d07b7551914f97f2bf8b9c79138ab14#:~:text=im%20%3D%20im.resize((im.size%5B0%5D*720//im.size%5B1%5D%2C720)%2C%20Image.LANCZOS)%20%23%20if%20you%20run%20out%20of%20GPU%20memory),so the PGN result image's resolution is low.But I noticed that your PGN reuslt was 3024 4032(my was 540 720).
Could you please tell me the detailed steps how you using the PGN to gernerate the *_PGN.png?
Thanks!

**Comment by MilesTheProwler** [comment]
Hi , did you try the model from textured_smplx\data\obj1\smpl\meshes\P01125-150055\000.obj ? I cannot apply the texture on 000.obj .

**Comment by qzane** [comment]
> 

https://github.com/qzane/textured_smplx/issues/7#issuecomment-1650676150

**Comment by qzane** [comment]
> Hi , did you try the model from textured_smplx\data\obj1\smpl\meshes\P01125-150055\000.obj ? I cannot apply the texture on 000.obj .

https://github.com/qzane/textured_smplx/issues/7#issuecomment-1650676150

**Comment by qzane** [comment]
> @qzane And I think it was PGN's problem.Here is mine PGN result and the repo's. [PGN.zip](https://github.com/qzane/textured_smplx/files/11341525/PGN.zip) Although their difference is small, it does lead to a difference in the results. Maybe the reason was picture resolution.I use [the line in your code](https://gist.github.com/qzane/4d07b7551914f97f2bf8b9c79138ab14#:~:text=im%20%3D%20im.resize((im.size%5B0%5D*720//im.size%5B1%5D%2C720)%2C%20Image.LANCZOS)%20%23%20if%20you%20run%20out%20of%20GPU%20memory),so the PGN result image's resolution is low.But I noticed that your PGN reuslt was 3024 4032(my was 540 720). Could you please tell me the detailed steps how you using the PGN to gernerate the *_PGN.png? Thanks!

Yes the white colors are from the background, which is definitely a segmentation issue. Unfortunately I don't remember how I got PGN working on high resolution images (maybe just run on a GPU with larger RAM?). Maybe you can try to remove the background with https://github.com/PeterL1n/BackgroundMattingV2 first.
